### ISSUE TITLE
Lambda update missing?

### ISSUE THREAD

**Issue by truncs** [mit-acl/mppi_numba#2]
Going through the barebones notebook seems like the lamba is set to 1 throughout the whole run of MPPI. Any specific reasons to not update lambda?

**Comment by xiaoyi-cai-acl** [comment]
Hi there---`lambda_weight` is a hyper-parameter defined in the `mppi_params` dictionary that can be tuned to your specific application, even at every time step. We chose `lambda_weight=1` and fixed the parameter dictionary throughout the MPPI run for simplicity, but you can choose any value you'd like. In fact, if you are doing re-planning at every time step, you can pass a new `mppi_params` dictionary that defines your problem (e.g., updated start and goal positions). Hope this helps.

**Comment by truncs** [comment]
Thanks for the reply. It does seem like the original paper just talks about lambda has a manually tuned hyperparameter. I got confused by this paper (https://openreview.net/pdf?id=fvfZKL1hCx)  where they automatically tune it.
